# make sure to supply your own environment variables
PROJECT_ID: <PROJECT_ID>
LOCATION: "us"
PROCESSOR_ID: <PROCESSOR_ID>
MIME_TYPE: "application/pdf"
FIELD_MASK: "text,entities,pages.pageNumber"
GCS_OUTPUT_URI: <GCS_OUTPUT_URI>
DATASET: <DATASET>
TABLE: <TABLE>